"""WAF / CDN detection scanner.

Tujuan: identifikasi WAF/CDN yang melindungi target sehingga laporan dapat
menyebut nama produk + memetakan tactic bypass yang khas. Sekaligus
mengidentifikasi WAF mode-permissive (block hanya warning, bukan reject)
yang sering jadi false sense of security.

Strategi (3 lapis):
    1. **Header & cookie fingerprint** pada response biasa.
    2. **Probe payload** ringan (`?id=' OR 1=1--`) — beberapa WAF menambah
       header `X-Sucuri-ID` / `X-CDN` hanya saat memblokir.
    3. **Status & body marker** umum (Cloudflare 1020, Akamai Reference,
       Imperva access denied, dst.).

Validasi: minimal **2 indikator** (atau 1 indikator yang sangat kuat
seperti `cf-ray` dengan body Cloudflare error page) sebelum lapor.
"""
from __future__ import annotations

import re
from urllib.parse import urljoin

from cyberloka.core import Finding, HttpClient, Severity, Target
from cyberloka.core.config import ScanConfig
from cyberloka.core.util import truncate

# (vendor, indicators-list)
# indicators: tuple (kind, regex_or_value, weight)
WAF_FINGERPRINTS = [
    ("Cloudflare", [
        ("header", "cf-ray", 3),
        ("header", "cf-cache-status", 2),
        ("header", "server", re.compile(r"cloudflare", re.I), 3),
        ("cookie", re.compile(r"__cf_bm|__cfduid|cf_clearance", re.I), 2),
        ("body", re.compile(r"cloudflare ray id|attention required.*cloudflare",
                            re.I), 3),
    ]),
    ("Akamai", [
        ("header", "x-akamai-transformed", 3),
        ("header", "x-akamai-request-id", 3),
        ("cookie", re.compile(r"_abck|ak_bmsc|bm_sv|bm_mi", re.I), 3),
        ("body", re.compile(r"reference\s*#\s*\d+\.\w+", re.I), 2),
    ]),
    ("Sucuri", [
        ("header", "x-sucuri-id", 3),
        ("header", "x-sucuri-cache", 2),
        ("body", re.compile(r"access denied.*sucuri", re.I), 3),
        ("header", "server", re.compile(r"sucuri/cloudproxy", re.I), 3),
    ]),
    ("Imperva / Incapsula", [
        ("cookie", re.compile(r"incap_ses|visid_incap|nlbi_", re.I), 3),
        ("header", "x-iinfo", 3),
        ("body", re.compile(r"incapsula|imperva", re.I), 2),
    ]),
    ("AWS WAF / CloudFront", [
        ("header", "x-amz-cf-id", 3),
        ("header", "x-amzn-requestid", 1),
        ("header", "via", re.compile(r"cloudfront", re.I), 3),
        ("body", re.compile(r"request blocked.*cloudfront|aws waf", re.I), 3),
    ]),
    ("F5 BIG-IP / ASM", [
        ("cookie", re.compile(r"\bBIGipServer|TS\w{6}", re.I), 3),
        ("header", "x-waf-event-info", 3),
        ("body", re.compile(r"the requested URL was rejected", re.I), 3),
    ]),
    ("Fastly", [
        ("header", "x-served-by", re.compile(r"cache-", re.I), 2),
        ("header", "fastly-debug-digest", 3),
        ("header", "x-fastly-request-id", 3),
    ]),
    ("Wordfence", [
        ("body", re.compile(r"generated by wordfence", re.I), 3),
        ("header", "x-wf-", 2),
    ]),
    ("ModSecurity", [
        ("body", re.compile(r"mod_security|modsecurity", re.I), 3),
        ("header", "x-mod-security-message", 3),
    ]),
    ("StackPath", [
        ("header", "x-sp-", 2),
        ("cookie", re.compile(r"sp-edge", re.I), 2),
    ]),
    ("Barracuda", [
        ("body", re.compile(r"barracuda networks", re.I), 3),
        ("header", "barra_counter_session", 3),
    ]),
    ("Cloudbric", [
        ("header", "server", re.compile(r"cloudbric", re.I), 3),
    ]),
    ("Reblaze", [
        ("cookie", re.compile(r"rbzid|rbzsessionid", re.I), 3),
    ]),
    ("Azure Front Door / WAF", [
        ("header", "x-azure-ref", 3),
        ("header", "x-fd-healthprobe", 1),
    ]),
]


def _score_indicators(headers: dict, cookies: dict, body: str
                      ) -> dict[str, list[str]]:
    """Return {vendor: [evidence,...]} untuk vendor yang minimal hit."""
    out: dict[str, tuple[int, list[str]]] = {}
    body_low = body[:4096].lower()
    for vendor, fps in WAF_FINGERPRINTS:
        score = 0
        evid: list[str] = []
        for fp in fps:
            kind = fp[0]
            if kind == "header":
                key = fp[1]
                expect = fp[2] if len(fp) >= 3 else None
                weight = fp[-1] if isinstance(fp[-1], int) else 1
                val = headers.get(key) or headers.get(key.lower())
                if val is None:
                    # Cari header by-name (case-insensitive)
                    for h, v in headers.items():
                        if h.lower() == key.lower():
                            val = v; break
                if val is None:
                    continue
                if isinstance(expect, re.Pattern):
                    if expect.search(val):
                        score += weight
                        evid.append(f"{key}={val[:50]!r}")
                else:
                    score += weight
                    evid.append(f"{key}={(val or '')[:50]!r}")
            elif kind == "cookie":
                rx = fp[1]; weight = fp[-1] if isinstance(fp[-1], int) else 1
                cookie_blob = "; ".join(f"{k}={v}" for k, v in cookies.items())
                if rx.search(cookie_blob):
                    score += weight
                    evid.append(f"cookie ~ {rx.pattern[:40]}")
            elif kind == "body":
                rx = fp[1]; weight = fp[-1] if isinstance(fp[-1], int) else 1
                if rx.search(body_low):
                    score += weight
                    evid.append(f"body marker {rx.pattern[:40]}")
        if score >= 3:  # threshold "yakin"
            out[vendor] = (score, evid)
    return out


def run(target: Target, config: ScanConfig) -> list[Finding]:
    findings: list[Finding] = []
    client = HttpClient(config)
    try:
        # Probe 1: GET /
        r1 = client.get(target.base_url, allow_redirects=False)
        if r1 is None:
            return findings
        cookies1 = {c.name: c.value for c in (r1.cookies or [])}
        scored = _score_indicators(dict(r1.headers), cookies1, r1.text or "")

        # Probe 2: payload ringan untuk memicu WAF
        probe_url = urljoin(target.origin + "/",
                            "?cyberloka_probe=' OR 1=1--&path=/etc/passwd")
        r2 = client.get(probe_url, allow_redirects=False)
        if r2 is not None:
            cookies2 = {c.name: c.value for c in (r2.cookies or [])}
            scored2 = _score_indicators(dict(r2.headers), cookies2, r2.text or "")
            # Gabungkan score
            for v, (s, e) in scored2.items():
                old = scored.get(v, (0, []))
                scored[v] = (old[0] + s, old[1] + e)

        if not scored:
            # Tidak ada WAF terdeteksi - infomatif saja
            findings.append(Finding(
                module="waf_detect",
                title="Tidak ada WAF/CDN umum yang terdeteksi",
                severity=Severity.INFO,
                description=(
                    "Cyberloka tidak menemukan tanda WAF/CDN umum (Cloudflare, "
                    "Akamai, Imperva, AWS WAF, F5, dll.). Bukan berarti tidak "
                    "ada — bisa jadi WAF self-hosted (ModSecurity / NAXSI / "
                    "Coraza) yang lebih senyap. Verifikasi manual disarankan."
                ),
                target=target.base_url,
                evidence="probe baseline + payload tidak men-trigger header/cookie WAF",
                cwe="CWE-200",
                confidence="firm",
                remediation=(
                    "Pertimbangkan deploy WAF (Cloudflare WAF, AWS WAF, "
                    "Imperva, atau ModSecurity self-hosted) terutama untuk "
                    "endpoint kritis (login, payment). WAF + rate-limit "
                    "adalah lapis pertahanan pertama vs scanner otomatis."
                ),
            ))
            return findings

        # Pilih vendor dengan score tertinggi
        top_vendor, (top_score, top_evid) = max(scored.items(),
                                                key=lambda kv: kv[1][0])
        # Lapor SEMUA vendor yang lolos threshold (multi-vendor stacking
        # umum: Cloudflare + AWS WAF + Wordfence).
        for vendor, (score, evid) in sorted(scored.items(),
                                            key=lambda kv: -kv[1][0]):
            findings.append(Finding(
                module="waf_detect",
                title=f"WAF/CDN terdeteksi: {vendor}",
                severity=Severity.INFO,
                description=(
                    f"Site dilindungi oleh {vendor}. Saat menjalankan "
                    "pengujian aktif lainnya, perhitungkan bypass-vector "
                    f"khas {vendor} (mis. header `CF-Connecting-IP` untuk "
                    "Cloudflare, encoded path untuk AWS WAF). False-negative "
                    "scanner sering disebabkan WAF — kombinasikan dengan "
                    "pen-test manual."
                ),
                target=target.base_url,
                evidence=truncate(
                    f"score={score}; indicators={evid[:5]}",
                    240,
                ),
                cwe="CWE-200",
                confidence="firm",
                remediation=(
                    f"WAF {vendor} terpasang — pastikan: "
                    "(a) rule set up-to-date, "
                    "(b) IP origin tidak bocor (cek modul `cf_origin`), "
                    "(c) bypass via subdomain non-protected ditutup, "
                    "(d) log WAF di-monitor."
                ),
            ))
    finally:
        client.close()
    return findings
